port: 3333
theme: 1
siteurl: 'https://www.bootstrapcdn.com'
description: 'The recommended CDN for Bootstrap, Font Awesome and Bootswatch.'
title_suffix: 'BootstrapCDN by StackPath'
authors:
  - name: Justin Dorfman
    twitter: jdorfman
    url: 'https://twitter.com/jdorfman'
  - name: Joshua Mervine
    twitter: mervinej
    url: 'https://twitter.com/mervinej'
    work:
      text: Heroku
      url: 'https://www.heroku.com/'
  - name: XhmikosR
    twitter: XhmikosR
    url: 'https://xhmikosr.io/'
favicon:
  uri: /assets/img/favicons/favicon.ico
stylesheet:
  - name: iubenda
    uri: /assets/css/privacy_policy.css
javascript:
  - name: clipboardjs
    uri: /assets/js/vendor/clipboard.min.js
  - name: main
    uri: /assets/js/main.js
friends:
  - name: SecurityTrails
    url: 'https://securitytrails.com/'
    nofollow: false
  - name: Bootstrap
    url: 'https://getbootstrap.com/'
  - name: nixCraft
    url: 'https://www.cyberciti.biz/'
  - name: Edubirdie
    url: 'https://edubirdie.com/'
    nofollow: false
  - name: FossHub
    url: 'https://www.fosshub.com/'
    nofollow: false
redirects:
  - name: legacy
    from: /legacy/
    to: /legacy/bootstrap/
  - name: alpha
    from: /alpha/
    to: /
  - name: beta
    from: /beta/
    to: /
  - name: bootswatch4
    from: /bootswatch4/
    to: /bootswatch/
